version: "3.9"

services:
  php:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: agent_php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./storage:/var/www/storage
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PY_WORKER_URL: ${PY_WORKER_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - python
      - mysql

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: agent_python
    expose:
      - "5001"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./python:/app

  mysql:
    image: mysql:8.0
    container_name: agent_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./storage/db:/var/lib/mysql

networks:
  default:
    name: ai_agent_net
