services:
  # ---------- PHP Web (Apache) ----------
  - type: web
    name: ai-agent-web
    env: docker
    plan: free
    dockerfilePath: ./app/Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://ai-agent-web.onrender.com
      - key: DB_HOST
        value: crossover.proxy.rlwy.net
      - key: DB_PORT
        value: "58825"
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: eoxenGaHVDRTTvQNDHIiadZjLlINEOek
      - key: PY_WORKER_URL
        value: http://ai-agent-worker:5001
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /

  # ---------- Python Worker (Flask) ----------
  - type: web
    name: ai-agent-worker
    env: docker
    plan: free
    dockerfilePath: ./python/Dockerfile
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false